version: "2"

services:

  web:
    build: .
    image: ctftraining/ciscn_2019_northeastern_china_web6
    restart: always
    ports:
      - "127.0.0.1:8083:8080"
      - "127.0.0.1:6379:6379"
    environment:
      - FLAG=flag{glzjin_wants_a_girl_firend}
